### ISSUE TITLE
Plugin won't save API key

### ISSUE THREAD

**Issue by papatistos** [helloworldkr/Askify-Obsidian-Sync#1]
I'm pasting in the api key into the plugin settings but when I navigate away from that page and go back, the key is gone.

I even tried what you did in the video, i.e. entering space and deleting it again. The key is never saved.

**Comment by helloworldkr** [comment]
Hi @tophee ,
Thanks for pointing out the issue.

The bug has been fixed.
you can try downloading the main.js again [Version 1.0.0]
