### ISSUE TITLE
Time stamp is not working

### ISSUE THREAD

**Issue by Gourav1910** [helloworldkr/Askify-Obsidian-Sync#3]
Hi, I took note in askify from my browser and I have put a time stamp. Later after I synced that note in obsidian I clicked on that time stamp but it started the video from beginning instead of the time of the time stamp. So please fix this issue so that video start running from the time of time stamp.

**Comment by helloworldkr** [comment]
@Gourav1910 Noted

**Comment by gustavostz** [comment]
@helloworldkr Can we expect this to be resolved soon?

**Comment by helloworldkr** [comment]
@gustavostz this issues fixed now
