### ISSUE TITLE
Sync isn't working or taking too much time too sync

### ISSUE THREAD

**Issue by gustavostz** [helloworldkr/Askify-Obsidian-Sync#4]
I'm trying to sync my notes with Obsidian, but after the first sync, it's not syncing the new files!

I checked the code and noticed that a request is made to the Google storage to get the notes, but there are notes that I created almost 30 minutes ago that still aren't in the storage!

![Image shows 2 notes created 27 minutes ago and 1 created 44 minutes ago](https://github.com/helloworldkr/Askify-Obsidian-Sync/assets/48111506/3a51db08-7367-44b1-882a-448fe62fc35d)

And when I downloaded the notes from the Google storage, I only had the first one:

![Image shows Google storage with only one file](https://github.com/helloworldkr/Askify-Obsidian-Sync/assets/48111506/9e383865-2d3a-4c67-b6fd-6c52fc769f74)

*(For security reasons I prefer to cover part of the zip file)

I'll wait until tomorrow to see if it's just a delay or if it doesn't work after the first sync and will update this thread.

But we already know that the problem isn't in the plugin code, but in the code that updates the Google storage.

**Comment by gustavostz** [comment]
After some time the sync finally worked, it seems that it has a delay of 1 hour. Which can be a problem for people like me who usually click the sync button because they want to work with that note

**Comment by helloworldkr** [comment]
Sure @gustavostz 
We had intentially added 1 hour delay for notes sync but will remove that as its causing user experience issue. It will take 2-3 weeks time as we intend to do it in our next release cycle.
Thansk a lot for sharing your experience with us.

**Comment by helloworldkr** [comment]
@gustavostz we have reduced new sync time from 1 hr to 5 minutes. Please check and confirm if its working for you.
