### ISSUE TITLE
FR: Change the display style of a timestamp from like `3 mins, 9 secs` to `03:09`

### ISSUE THREAD

**Issue by XMB-7** [helloworldkr/Askify-Obsidian-Sync#5]
When exporting a note as markdown, the display style of a timestamp is just consistent with the editor in the browser.
![image](https://github.com/helloworldkr/Askify-Obsidian-Sync/assets/65625632/5abb869d-d810-4729-9119-7e954e8bcf7a)

However, when synced to obsidian with this plugin, the names of the links to the video are redundant.
![image](https://github.com/helloworldkr/Askify-Obsidian-Sync/assets/65625632/41ff155b-f4ff-4ea1-bce6-0bcc9bd0a889)

Therefore, it would be great if users could choose the preferred display style for timestamps.

**Comment by helloworldkr** [comment]
Hi @XMB-7,

Thank you for bringing this to our attention! We've updated the timestamp display to align with the one on Askify. If you have any additional requirements or suggestions, please feel free to share them with us. We're more than happy to incorporate any further improvements you may have in mind.

**Comment by XMB-7** [comment]
Thanks for your time on this quick update, looking forward to the release. 
I also have some ideas on Askify but less relevant to this plugin, so not sure if this repo is the appropriate place to communicate.

**Comment by helloworldkr** [comment]
@XMB-7 Feel free to reach out to us directly at [kishlay@askify.video](mailto:kishlay@askify.video) or [pratyush@askify.video](mailto:pratyush@askify.video). We look forward to receiving your messages and any additional feedback you might have. 😊
